# Generated by Django 5.1.4 on 2025-03-12 08:09

from django.db import migrations, models

def populate_unique_emails(apps, schema_editor):
    CustomUser = apps.get_model('Taxi', 'CustomUser')
    for user in CustomUser.objects.all():
        # Use first_name if available, otherwise fall back to phone_number
        base_name = user.first_name if user.first_name else user.phone_number
        # Generate a unique email
        user.email = f"{base_name.lower().replace(' ', '_')}@example.com"
        # Ensure uniqueness by appending ID if needed
        if CustomUser.objects.filter(email=user.email).exclude(id=user.id).exists():
            user.email = f"{base_name.lower().replace(' ', '_')}_{user.id}@example.com"
        user.save()
        

class Migration(migrations.Migration):
    dependencies = [
        ('Taxi', '0001_initial'),  # Adjust this
    ]
    operations = [
        # Step 1: Add the email field as nullable temporarily
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(
                max_length=254,
                null=True,  # Temporary nullable
                blank=True,
                unique=True,
            ),
        ),
        # Step 2: Populate with unique emails
        migrations.RunPython(populate_unique_emails),
        # Step 3: Alter the field to non-nullable
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(
                max_length=254,
                null=False,
                blank=False,
                unique=True,
            ),
        ),
    ]



# import django.utils.timezone
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('Taxi', '0001_initial'),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='customuser',
#             name='email',
#             field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
#             preserve_default=False,
#         ),
#         migrations.AddField(
#             model_name='customuser',
#             name='is_email_verified',
#             field=models.BooleanField(default=False),
#         ),
#     ]
