# Generated by Django 5.1.4 on 2025-03-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0002_customuser_email_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
