# Generated by Django 5.1.4 on 2025-03-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0003_customuser_is_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequest',
            old_name='id',
            new_name='ridrequest_id',
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='seats_requested',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
