# Generated by Django 5.1.4 on 2025-03-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0005_rename_id_carpoolride_carpoolride_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='id',
            new_name='wallet_id',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
