# Generated by Django 5.1.4 on 2025-03-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0006_rename_id_wallettransaction_wallet_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwallet',
            old_name='id',
            new_name='userWalletid',
        ),
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='wallet_id',
            new_name='walletTransactionid',
        ),
    ]
