# Generated by Django 5.1.4 on 2025-04-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0008_rename_id_payment_paymentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
