# Generated by Django 5.1.4 on 2025-04-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0009_vehicle_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_available',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
