# Generated by Django 5.1.4 on 2025-04-13 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0010_remove_vehicle_is_available_customuser_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpoolride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
