# Generated by Django 5.1.4 on 2025-04-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0011_alter_carpoolride_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolride',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
