# Generated by Django 5.1.4 on 2025-04-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0012_carpoolride_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In_progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
