# Generated by Django 5.1.4 on 2025-05-07 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0014_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='carpoolride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Taxi.carpoolride'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
    ]
