# Generated by Django 5.1.4 on 2025-05-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0018_wallettopuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettopuprequest',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('crypto', 'Crypto'), ('mock', 'Mock')], default='mock', max_length=20),
        ),
    ]
