# Generated by Django 5.1.4 on 2025-05-11 23:49

from django.db import migrations, models
def populate_total_amount_paid(apps, schema_editor):
    CarpoolRide = apps.get_model('Taxi', 'CarpoolRide')
    for ride in CarpoolRide.objects.filter(status='completed'):
        accepted_requests = ride.requests.filter(status='accepted', payment_status='paid')
        total = sum(float(ride.contribution_per_seat) * req.seats_requested for req in accepted_requests)
        ride.total_amount_paid = total
        ride.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0020_profilestats_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolride',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.RunPython(populate_total_amount_paid),
    ]
