# Generated by Django 5.1.4 on 2025-05-12 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0021_carpoolride_total_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='carpoolride',
            index=models.Index(fields=['origin', 'destination'], name='Taxi_carpoo_origin_9c0532_idx'),
        ),
        migrations.AddIndex(
            model_name='carpoolride',
            index=models.Index(fields=['departure_time'], name='Taxi_carpoo_departu_0707b7_idx'),
        ),
        migrations.AddIndex(
            model_name='carpoolride',
            index=models.Index(fields=['status', 'is_full'], name='Taxi_carpoo_status_f27aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['status'], name='Taxi_ridere_status_5bc0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['passenger', 'ride'], name='Taxi_ridere_passeng_2959f4_idx'),
        ),
        migrations.AddField(
            model_name='ridematch',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridematch',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_matches', to='Taxi.carpoolride'),
        ),
        migrations.AlterUniqueTogether(
            name='ridematch',
            unique_together={('passenger', 'ride')},
        ),
    ]
