# Generated by Django 5.1.4 on 2025-05-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0022_ridematch_carpoolride_taxi_carpoo_origin_9c0532_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release'), ('escrow_refund', 'Escrow Refund')], max_length=25),
        ),
    ]
