# Generated by Django 5.1.4 on 2025-05-15 01:51

from django.db import migrations, models
import uuid
def assign_uuids_to_messages(apps, schema_editor):
    Message = apps.get_model('Taxi', 'Message')
    for msg in Message.objects.all():
        msg.message_id = uuid.uuid4()
        msg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0024_alter_customuser_profile_picture_message'),
    ]

    operations = [
        # Step 1: Add temporary nullable UUIDField
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),

        # Step 2: Assign UUIDs to existing rows
        migrations.RunPython(assign_uuids_to_messages),
        
        # Step 3: Remove the old auto-generated 'id' field
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),

         # Step 4: Alter the new UUID field to be primary
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
    ]