# Generated by Django 5.1.4 on 2025-05-19 11:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0025_auto_20250515_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
