# Generated by Django 5.1.4 on 2025-05-30 23:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0028_customuser_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
