# Generated by Django 5.1.4 on 2025-05-30 23:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0029_notification_notification_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
