# Generated by Django 5.1.4 on 2025-06-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0031_alter_carpoolride_status_alter_riderequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('cancellation', 'Cancellation'), ('request', 'Request'), ('declined', 'Declined')], max_length=20),
        ),
    ]
