# Generated by Django 5.1.4 on 2025-06-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0032_alter_notification_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['created_at'], name='Taxi_wallet_created_d6c922_idx'),
        ),
    ]
