# Generated by Django 5.1.4 on 2025-06-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0034_alter_vehicle_vehicle_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlocation',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='fraudlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ntsaverificationlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewed_user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ride',
        ),
        migrations.DeleteModel(
            name='Dispute',
        ),
        migrations.DeleteModel(
            name='DriverLocation',
        ),
        migrations.DeleteModel(
            name='FraudLog',
        ),
        migrations.DeleteModel(
            name='NTSAVerificationLog',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
