# Generated by Django 5.1.4 on 2025-06-11 11:37

import Taxi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0036_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=Taxi.models.user_profile_picture_upload_path, validators=[Taxi.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to=Taxi.models.vehicle_photo_upload_path, validators=[Taxi.models.validate_image]),
        ),
    ]
